# Generated by Django 4.2.7 on 2023-11-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('identification', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mail', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, default='', max_length=3, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
