# Generated by Django 4.2.7 on 2023-11-05 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_start', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_end', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('id_Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.plan')),
            ],
        ),
    ]
