# Generated by Django 4.2.7 on 2023-11-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_plan_plan_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
