# Generated by Django 4.2.7 on 2023-11-13 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_client_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_end',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
