# Generated by Django 4.2.7 on 2023-11-13 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_alter_plan_category_alter_plan_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
