# Generated by Django 4.2.7 on 2023-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0005_alter_plan_category_alter_plan_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('Plata', 'Plata'), ('Platino', 'Platino'), ('Oro', 'Oro')], default='', max_length=100),
        ),
    ]
