# Generated by Django 4.2.7 on 2023-11-13 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_alter_plan_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
    ]
