# Generated by Django 4.2.7 on 2023-11-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_remove_plan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.plan')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='plans',
            field=models.ManyToManyField(related_name='clients', through='Client.PlanClient', to='Client.plan'),
        ),
    ]
