# Generated by Django 4.2.7 on 2023-11-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0008_planclient_client_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='clients', through='Client.PlanClient', to='Client.plan'),
        ),
    ]
