# Generated by Django 4.2.7 on 2023-11-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0009_alter_client_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
