# Generated by Django 4.2.7 on 2023-11-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_client_activate_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
