# Generated by Django 4.2.7 on 2023-11-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='occupation',
            field=models.CharField(choices=[('Plata', 'Plata'), ('Platino', 'Platino'), ('Oro', 'Oro'), ('Platino', 'Platino'), ('Oro', 'Oro')], default='', max_length=20),
        ),
    ]
