# Generated by Django 4.2.7 on 2023-11-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_employee_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='occupation',
            field=models.CharField(choices=[('Conectividad', 'Conectividad'), ('Pagos', 'Pagos'), ('Env', 'Env'), ('Privacidad', 'Privacidad')], default='', max_length=20),
        ),
    ]
