# Generated by Django 4.2.7 on 2023-11-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
    ]
