# Generated by Django 4.2.7 on 2023-11-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_remove_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Conectividad', 'Conectividad'), ('Pagos', 'Pagos'), ('Env', 'Env'), ('Privacidad', 'Privacidad')], default='', max_length=20),
        ),
    ]
