# Generated by Django 4.2.7 on 2023-11-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_alter_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
