# Generated by Django 4.2.7 on 2023-11-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_employee_activate_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='level',
            field=models.CharField(blank=True, choices=[('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Critico', 'Critico'), ('Prioritario', 'Prioritario')], max_length=100, null=True),
        ),
    ]
