# Generated by Django 4.2.7 on 2023-11-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_client_activate_client_password'),
        ('Employee', '0009_alter_ticket_description_alter_ticket_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
    ]
