# Generated by Django 4.2.7 on 2023-11-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_client_activate_client_password'),
        ('Employee', '0010_ticket_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
    ]
