# Generated by Django 4.2.7 on 2023-11-06 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('nit', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('mail', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('q_domains', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('bank_account', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('available', models.BooleanField(default=True)),
                ('plataform', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('id_Distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.distributor')),
            ],
        ),
    ]
