# Generated by Django 4.2.7 on 2023-11-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='bank_account',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Premium', 'Premium')], default='', max_length=20),
        ),
    ]
