# Generated by Django 4.2.7 on 2023-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_distributor_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='category',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Premium', 'Premium')], default='', max_length=20),
        ),
    ]
