# Generated by Django 4.2.7 on 2023-11-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_domain_plataform'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
