# Generated by Django 4.2.7 on 2023-11-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_domain_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
