# Generated by Django 4.2.7 on 2023-11-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
