# Generated by Django 4.2.7 on 2023-11-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0010_client_activate_client_password'),
        ('Admin', '0008_alter_domain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='id_Client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.client'),
        ),
        migrations.AddField(
            model_name='domain',
            name='id_Plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Client.plan'),
        ),
    ]
