# Generated by Django 4.2.7 on 2023-11-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_domain_id_client_domain_id_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='id_Client',
            new_name='id_Client_id',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='id_Distributor',
            new_name='id_Distributor_id',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='id_Plan',
            new_name='id_Plan_id',
        ),
    ]
