# Generated by Django 4.2.7 on 2023-11-23 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_rename_id_client_domain_id_client_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='id_Client_id',
            new_name='id_Client',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='id_Distributor_id',
            new_name='id_Distributor',
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='id_Plan_id',
            new_name='id_Plan',
        ),
    ]
