# Generated by Django 4.2.7 on 2023-11-26 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_rename_id_client_id_domain_id_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
