# Generated by Django 4.2.7 on 2023-11-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_domain_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='created_at',
        ),
    ]
