# Generated by Django 4.2.7 on 2023-11-05 23:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0002_plan_plan_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('h_entry', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_Card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pay.card')),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
            ],
        ),
    ]
