# Generated by Django 4.2.7 on 2023-11-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0002_alter_pay_amount_alter_payment_method_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='type',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='', max_length=200),
        ),
    ]
