# Generated by Django 4.2.7 on 2023-11-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0003_pay_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='h_entry',
            new_name='d_expiration',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='number',
        ),
    ]
