# Generated by Django 4.2.7 on 2023-11-13 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0004_rename_h_entry_card_d_expiration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='name',
        ),
    ]
