# Generated by Django 4.2.7 on 2023-11-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0006_pay_id_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='id_Distributor',
        ),
    ]
