# Generated by Django 4.2.7 on 2023-11-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_remove_domain_created_at'),
        ('Pay', '0007_remove_pay_id_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='id_Distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.distributor'),
        ),
    ]
