# Generated by Django 4.2.7 on 2023-11-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0008_pay_id_distributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='d_expiration',
        ),
    ]
