# Generated by Django 4.2.7 on 2023-11-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0009_remove_card_d_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='type',
        ),
        migrations.AddField(
            model_name='card',
            name='ccv',
            field=models.IntegerField(default=0),
        ),
    ]
